### ISSUE TITLE
Simplify questions API / documentation

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#129]
- Users shouldn't have to know about the difference between `LinearQuestion`, `LogQuestion`, `LinearDateQuestion`, etc., if they only use common functionality
- Foretold- and Metaculus questions should have the same interface

**Comment by brachbach** [comment]
I think anything Foretold-related is less important, now that we're no longer actively working on integrations/projects with Foretold.

But the first bullet here still seems important

**Comment by zmpster** [comment]
@brachbach What about PredictIt? Seems like you added a PredictIt integration since this issue was filed. I was thinking of unifying a platform-independent questions interface before adding any new platforms for https://github.com/oughtinc/ergo/issues/232. Would that be helpful?

**Comment by stuhlmueller** [comment]
I think it could be - share a spec ahead of implementation so that we can discuss?

**Comment by zmpster** [comment]
Okay, spent a bunch of time yesterday looking through the "question" classes. I still have a bunch of questions (pun slightly intended) about the current design, but my initial thought is to is decouple all the manipulation of distributions happening in `ContinuousQuestion` (so `prepare_logistic`, `prepare_logistic_mixture`, and `get_submission_from_samples` and move them to either a general, non-Metaculus ContinuousQuestion class or into the distributions code. It seems like the only Metaculus-specific thing they are doing is using the scale and bounds info, but those could theoretically exist on any platform. Very interested to hear your thoughts or hop in on a call!

**Comment by zmpster** [comment]
Also, first of my quick questions is why in `get_submission_from_samples` do we set `"num_components": 3`? Seems like a somewhat magical number to me, but I could be missing something.

**Comment by brachbach** [comment]
re: moving `prepare_logistic`, `prepare_logistic_mixture`, and `get_submission_from_samples` out of Metaculus-specific code -- I actually think we should leave them in Metaculus-specific code.

The only reason to make + submit a logistic mixture is that that's the format that Metaculus requires -- just a straight-up histogram like our `PointDensity` would generally make more sense. I don't think any other platform requires a logistic mixture.

That said, I definitely think reorganizing the code could make sense. E.g. we could have a `ContinuousQuestion` class shared between platforms, a `MetaculusQuestion` class, and a `ContinuousMetaculusQuestion` class that inherits from both. TBC not saying that you _should_ do that, just that it'd be sensible 

re: why is "num_components": 3 -- yeah there's no good reason :). We actually do 5 components in Elicit, which is the max that Metaculus allows. And I think that lets us get a better fit. So would be good to change to 5 in Ergo

Hope that helps, interested to hear more about how you're thinking of simplifying things!

**Comment by zmpster** [comment]
Sorry for the delay here, was on a trip this last week. Anyway, what you say makes sense as a reason to not refactor those three methods. I didn't realize that Metaculus had an idiosyncratic way of accepting prediction distributions.

With that, my plan is to first make a platform-independent questions interface (I come from a primarily-Java background, so please do let me know if any of these plans are not the typical pattern in Python) with the following methods:
`refresh()`
`sample_community()`
`get_text()` (or maybe `get_name()`, just something that identifies the text of the question

then a BinaryQuestion class with the following methods:
`get_community_prediction()`
`submit(p: float) -> requests.Repsonse`

and a ContinuousQuestion with:
`community_dist() -> dist.Distribution:` (this one is currently in `MetaculusQuestion`, but seems like you wouldn't want to use it, except for a "continuous question", though I could be wrong here)
`submit_from_samples(samples: Union[pd.Series, np.ndarray]) -> requests.Response`

Let me know if this makes sense! I'm also happy to hop on a call if that's convenient!
