### ISSUE TITLE
Improve docs re: using ergo in a Colab via a local runtime

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#133]
Either remove mention of this or add some of the following points:

fyi, for me, in order to run Colab w/ a local version of ergo, between step 2 (entering the poetry virtualenv) and step 3 (starting the Jupyter server), I needed to run the following commands
pip install jupyter_http_over_ws (needed for the Colab to connect)
pip install --upgrade pip (python 3.6.9 comes w/ pip 18.1 but that doesn’t work to install google.colab below)
pip install google.colab (needed to avoid ModuleNotFoundError: No module named 'google' in Colab)
pip install --upgrade ipykernel (installing google.colab uninstalls the ipykernel 5.2.1 and installs ipykernel 4.6.1, but this older version throws an error when you try to connect to the Jupyter server from a Colab, so we need to reinstall the newer version)
i figured i’d put this here in case anyone is having similar issues

Ben Rachbach  15 minutes ago
Ah, now I remember that that 1st step is the thing that I had to do to get it working!
I think that, for whatever reason, I didn’t have to do the other 3 things ,not sure why
@zak @andreas, what’s your experience been with using the local runtime? Mine hasn’t been great (dependencies work differently from Colab, sometimes ergo fails to refresh when you restart the runtime), so I’ve been wondering if we should just stop doing it

zak  7 minutes ago
so far it’s been ok for me (after ironing out the issues above); my plan today is to do mostly ergo development, so i’ll take note on how smoothly it goes

zak  6 minutes ago
(also unclear we need a uniform policy on this; tho i guess we need a uniform policy on what to say in the docs about local development)

**Comment by zjmiller** [comment]
Also maybe mention using `pyenv` to install python 3.6.9.
