### ISSUE TITLE
Memoization

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#137]
This would make it possible to structure William's Epifor model using smaller functions

**Comment by stuhlmueller** [comment]
https://webppl.readthedocs.io/en/master/functions/other.html#mem

**Comment by stuhlmueller** [comment]
Temporary hack:

```py
memoized_functions = []

def mem(func):
    func = lru_cache(None)(func)
    memoized_functions.append(func)
    return func

def clear_mem():
    for func in memoized_functions:
        func.cache_clear()

def model():
    clear_mem()
    ...
```

**Comment by brachbach** [comment]
Adding to the El Paso issue board because I think that this is a bit of a weird, hacky, and magical part of the El Paso model for now

@stuhlmueller do you have specific thoughts on how to make this better, other than just integrating the existing functions used in the Colab into `ergo`?

**Comment by stuhlmueller** [comment]
Done in #194
