### ISSUE TITLE
Simple, consistent API for graphing predictions on continuous questions

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#139]
Right now graphing predictions on continuous questions is really confusing.

I mostly created the API, and [here](https://colab.research.google.com/drive/17w7YUJJA3gJD8ketp6ZQtDiaeV1foTc7#scrollTo=UBjzm9nhdyD2&line=1&uniqifier=1) I couldn't remember how to get my prediction and the community prediction on the same graph :|

I think we should probably just have one function that users are meant to use, `show_prediction(self, samples=None, show_community=True)`

This new function would be largely the same as the current `show_submission` as seen in the last 2 plots here: https://github.com/oughtinc/ergo/blob/master/notebooks/community-distributions.ipynb

i.e. you should be able to plot the samples, the logistic mixture, and the community prediction together

This would replace:
1. `show_performance`: we don't really use this right now and should just get rid of it I think
2. `show_submission`: this is currently what we mainly use. But I think `show_prediction` is a better name than `show_submission`
3. `show_community_prediction`: currently how you see the community prediction by itself. I think just calling `show_prediction()` or `show_prediction( show_community=True)` would simplify things
4. the current `show_prediction`. This isn't actually meant to be used by users currently (it shows a prediction based on mixture params, we just use it as part of other functions)

Maybe most important, our new API should work consistently across all 3 types of continuous questions; there's a lot of heterogeneity right now

**Comment by stuhlmueller** [comment]
Also consider how this interacts with ggplot grammar for graphics. Maybe some of these options should be layers that can be added to plots.

**Comment by brachbach** [comment]
Labeling as `el-paso-urgent` because this annoyed me [here](https://colab.research.google.com/drive/17w7YUJJA3gJD8ketp6ZQtDiaeV1foTc7#scrollTo=UBjzm9nhdyD2&line=1&uniqifier=1) while working on an El Paso question.

Assigning to Dan because of his ggplot skillz

**Comment by djthorne** [comment]
With the current PR the two plotting functions for every question are:
show_community_prediction(self)
show_prediction(self, samples, show_community=False)

**Comment by brachbach** [comment]
cool, seems fine to me!

**Comment by djthorne** [comment]
Slight amendment to the signatures
show_community_prediction(
        percent_kept: float = .95
        side_cut_from: str = "both",
        num_samples: int = 1000)

This will give people the ability to control a 'zoom'
