### ISSUE TITLE
Handling for "Ridge" predictions

### ISSUE THREAD

**Issue by AABoyles** [oughtinc/ergo#167]
Metaculus allows binary and continuous question types. It does not support any non-binary discrete question types (e.g. over nominal categories, ordinal categories, integers, or any discrete subset of real numbers). There are a couple of ways for question authors to hack around this limitation. In the case of small ranges of integers, the typical approach is to model the range as continuous and then don't worry about it. However, predictors are clever, and leverage the multi-modal distribution system to maximize their scores by creating minimally-dispersed curves and centering them on the likeliest integers, resulting in "ridge" patterns in their probability density diagrams (or "stair" patterns in the equivalent cumulative density diagrams). [See this question for example.](https://pandemic.metaculus.com/questions/4030/how-many-of-the-twelve-states-hit-hardest-by-covid-19-before-2020-08-01-will-be-states-that-voted-trump-in-2016/)

It would be super-cool if ergo had a special handler for such questions--like, we could do modelling normally as though it were a continuous phenomenon, and then call the handler to collapse the probability mass into the five likeliest integers, automatically weighted to match the prescription by the continuous version of the model.

**Comment by stuhlmueller** [comment]
Discussed with Tony earlier today: Next step here is to make a notebook that demonstrates using Ergo for predictions on a "discrete" question. The Ergo model can sample integers directly and we can test how well the logistic mixture fitting works in that case.
