### ISSUE TITLE
Add an Optimizer

### ISSUE THREAD

**Issue by AABoyles** [oughtinc/ergo#174]
**This may be dire overkill**, but in [Community Distributions](https://github.com/oughtinc/ergo/blob/master/notebooks/community-distributions.ipynb), you use the distributions from two questions to infer a solution to a third question. This is a nifty use case! However, why is the third question privileged? After all, we can use any two of those questions to predict on the remaining one. Moveover, we could do so recursively, bringing the solutions closer to tripartite consistency on each iteration... Or we could add an optimizer that could solve problems of this variety for us.

**Comment by stuhlmueller** [comment]
I think this is crucial functionality:
https://github.com/oughtinc/ergo/issues/59

**Comment by AABoyles** [comment]
Oh, nice! Apologies for the duplication!

**Comment by stuhlmueller** [comment]
You posting issues and me pointing out if they exist is a good workflow, it's hard to find existing issues :-)

**Comment by AABoyles** [comment]
True that!

**Comment by AABoyles** [comment]
Some extensions:

- Weight by credence: pass in a list of credences you assign to the community distribution on each question and adjust the question in proportion to (some function of) those credences.
- Weight by census: adjust the question according to some function of the number of predictions or predictors (or both), relative to the number of predictions (or predictors or both) on the other questions being optimized against.

**Comment by stuhlmueller** [comment]
Good ideas! Also post to the other issue so that we don't overlook it when we implement it?
