### ISSUE TITLE
Better ability to handle/recover when logistic mixture fitting fails

### ISSUE THREAD

**Issue by william-r-s** [oughtinc/ergo#177]
I distribution fitting failed for a couple questions in the El Paso colab, which I think was mainly because of some outliers in the samples.
There wasn't a way to catch that this had happened (an error message was printed, but no exception was raised).
It would be good to be able to specify that we should throw out outliers in get_submission_from_samples (like the percent_kept keyword). We should consider doing this by default (because we're doing this for the graphs anyways).

Here's the code that I used to patch it for now
      # Clip extreme values for questions that we had issues fitting
      (sample_min, sample_max) = np.quantile(q_samples, [0.02, 0.98])
      q_samples = q_samples[(q_samples >= sample_min) & (q_samples <= sample_max)]

**Comment by djthorne** [comment]
There is a get_central_quantiles static method of the MetaculusQuestion. I'm not sure if it is better as It is a bit over-engineered for this in that it allows you to choose if you want to cut from a particular side, but you  could use it in your first line e.g.:
(sample_min, sample_max) = {question_instance}.get_central_quantiles(q_samples, percent_kept=.96)

One thing to note is that using the quantile function like your patch is not guaranteed to return a fixed proportion of samples (e.g. inner 95% of a (100,1) sample could be length 95  for sample1 and length 96 for sample2.) If that is an issue I have a method that returns fixed-length inner quantiles.
