### ISSUE TITLE
Move data munging elsewhere

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#191]
We'd like to move the data munging, and other non-model code that is specific to El Paso and thus shouldn't be added to `ergo`, elsewhere, so that the Colab is cleanly just the actual El Paso model.

I'm not sure exactly where this code should live, some ideas:
- code lives in an "El Paso model" repo
- code lives in gists

Of course we'll also need to figure out how to load in the code for use in the Colab -- probably easiest to load it as a standard Python package

**Comment by stuhlmueller** [comment]
How about an `examples/el-paso` folder in the Ergo repo?

**Comment by brachbach** [comment]
Duplicate of #178
