### ISSUE TITLE
Make Colab version control less terrible

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#192]
Right now, the only way we're able to do version control with Colabs is to load the "master" version and the "branch" version, visually compare them, and copy code over from "branch" to "master" as appropriate

It'd be really great to be able to do something more like normal version control, where we can use something like git to help us compare and merge versions

My guess is that the way to do this is to use `.ipynb` files in some way

Here are some ideas for ways to do that well:
1. https://nextjournal.com/schmudde/how-to-version-control-jupyter
2. http://timstaley.co.uk/posts/making-git-and-jupyter-notebooks-play-nice/

I'm not sure which of the ideas mentioned here (or which other solution) is best

Tentatively I like the idea of just saving clean versions of the `.ipynb`s (without the notebook output) and diffing those using git

I'll probably try that out in the near future, so assigned myself to this issue

**Comment by brachbach** [comment]
My updated guess at the best way to do this:

1. Before submitting a PR, use [`nbconvert`](https://nbconvert.readthedocs.io/en/latest/) to save the notebook as a Python file
2. While reviewing the PR, use [reviewnb](https://www.reviewnb.com) (free for open source) to compare the notebooks

I'll start playing with these ideas

**Comment by AABoyles** [comment]
FWIW, I suggest adopting a workflow based on [nbdime](https://nbdime.readthedocs.io/en/latest/).

**Comment by brachbach** [comment]
@AABoyles , is there a way to use nbdime on Github?

Or just locally with git?

**Comment by AABoyles** [comment]
Just local, so far as I know.
