### ISSUE TITLE
Define relationships between questions in a more intuitive and better way

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#200]
Right now, relationships between questions are defined by:

1. identify parameters that are important across multiple questions, like `daily_infections(date) = number of new infections on [date]`
2. when you need one of these parameter values, just call the function that gives you the value

this is pretty rudimentary and doesn't allow for 2-way relationships or "conditioning based on model results". As an example of what you'd want to do, if you get an absurdly high result for `mean_infections_peak345()`, you'd like to be able to decrease your estimate for `daily_infections`

it'd be nice to be able to express interdependences in some intuitive way that both made the model easier to understand and created those 2-way relationships

I think the full version of this is probably one of the core design and engineering challenges for `ergo`

But we might be able to do an interesting partial version now for El Paso

@andreas @jungofthewon @zjmiller, any thoughts on this?

**Comment by stuhlmueller** [comment]
[The minimal update issue](https://github.com/oughtinc/ergo/issues/59) would result in 2-way relationships.
