### ISSUE TITLE
Get our model externally reviewed

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#201]
Something like what [William described on Slack](https://ought-inc.slack.com/archives/GUM11Q8S2/p1588003660008900)

**Comment by brachbach** [comment]
@jungofthewon are you interested in this by any chance?

(I think I someone else could also be a good person to do it)

**Comment by jungofthewon** [comment]
Do you still need an answer to this? If so, do you mean interested in seeing it happen or doing it myself?

**Comment by brachbach** [comment]
I meant interested in doing it yourself

But I've gotten started on it in [this Typeform](https://admin.typeform.com/form/mFOEoo/create)

**Comment by brachbach** [comment]
Update: the Typeform ([create link](https://admin.typeform.com/form/mFOEoo/create), [share link](https://ought.typeform.com/to/mFOEoo)) is my best effort at this so far, but I don't think would provide very useful information.

I think what we need at this point is for people to review the whole model and give very holistic feedback.

I'll plan to reach out to people tomorrow.

**Comment by jungofthewon** [comment]
Cool - agree that reviewing live is probably best.

**Comment by brachbach** [comment]
The plan is to do this in 2 phases:

Phase 1 (start today): help reviewers really understand the model, likely spending 30 min or so talking them through it. Freeform feedback about how the model could be better

Phase 2 (start Fri): reviewers predict how likely our model is to beat the community/what mixture ratio between our model and the community is likely to end up having made the best prediction (see #221). (Reviewers can still suggest ways to make our model better)

**Comment by brachbach** [comment]
Update: for Phase 1, I reached out to a few people and will be joining a call with Jungwon tomorrow.
