### ISSUE TITLE
Generalize the El Paso model to all other counties covered by the Columbia data (< 8 hrs)

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#210]
For the purpose of this issue, we should keep the "UX" of this really simple -- maybe, there's a cell in the notebook where you specify which country you want to run the model for (and the model runs for one county at a time)

TBC the thing I think we should do is keep it really simple, I'm not attached to that UX per se, it just seemed really simple

**Comment by brachbach** [comment]
I've realized now that for this to work, we'll also need historical data for other counties.

The Columbia model gets this from USA Facts, as they [describe](https://github.com/shaman-lab/COVID-19Projection)

**Comment by brachbach** [comment]
@djthorne great work on this [so far](https://colab.research.google.com/drive/19IrlAym7NAbShZxyxCy-XTkMLWkPetqo?usp=sharing)!

I discussed with Andreas a bit how we should move forward, and we're thinking:

1. You'll continue to be the one to work on this. If possible, we should carve out a small enough scope that you'll have a good shot of finishing something by the end of the weekend
2. We will indeed have one notebook with the general "any county" code as well as the El Paso-specific stuff. I think the way to do it is to have an El Paso-specific section at the end that uses the general "any county" functions from above (not sure exactly what that'll need to look like). We'd like the model to work for all counties but to be extendable with specific information about any particular county
3. The questions that the model is answering (currently the `@question`s under "
El Paso questions") will need to be expressed as just functions rather than as ergo Metaculus question instances, since we'll be using them for all counties and of course the Metaculus questions only exist for El Paso
4. That means that we'll need to figure out a way to plot these, given that we can't just straightforwardly call `show_prediction`. There are a number of ways to do this:
  a. separate out the plotting code from MetaculusQuestion in the core ergo codebase: https://github.com/oughtinc/ergo/issues/270. The most principled solution, and something that we're pretty sure we want to do at some point. 
  b. something like option a., but we just add the new plotting functions to `contrib/`, make no changes to ergo core, and have a lower bar for the code
  c. for maximum hackiness: make a MetaculusQuestion from data, without actually interacting with the Metaculus API, for the sole purpose of showing each graph. Like what we're doing [here](https://github.com/oughtinc/ergo/blob/master/tests/test_metaculus.py) with `mock_log_question`

consider do a. if you think it will be relatively easy and quick to do well, otherwise whatever works between b, c, or something else

5. Definitely LMK if you have any questions!

**Comment by djthorne** [comment]
For 4, I think option b) is the way to go for now. a) shouldn't be tough, but a bit under-specified atm.

**Comment by djthorne** [comment]
My plan of attack:
Focus on making

**Comment by djthorne** [comment]
Quick update, talked to Andreas a briefly and it seems like the example of augmenting a general model with specific data is the most important bit, so I'll focus on that after the plots. I would have a plan for making the general model better if we want to move forward with that.
