### ISSUE TITLE
In show_prediction, have an option to show both samples form our model as well as samples from the logistic mixture we fit to the model results to submit our predictions

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#215]
Right now, since you can only have one `samples`, you can only see one or the other.

Being able to see both would be helpful for debugging cases where the logistic mixture diverges from the model samples

**Comment by djthorne** [comment]
Option 1, simple: 'You get what you pass'
the function accepts samples and SubmissionMixtureParams object. If you pass both, you get both.

Option 2: You specify what you want
This allows you pass samples and say 'I just want the fitted model', or 'I want both'

This is nicer for the user in that they won't need to call and handle the fit function, but it will be a bit uglier code-wise and the user will also need to set some boolean flags in show_prediction

@brachbach preference?
