### ISSUE TITLE
Choose how much to mix in the community distribution using a slider

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#221]
Would make it much easier to predict what mixture of our model plus the community prediction will end up being the best prediction (see #201)

The graph should render pretty quickly (less than a second)

**Comment by brachbach** [comment]
@stuhlmueller I tried to capture our discussion on the call here and in #201

**Comment by stuhlmueller** [comment]
Another idea from the call: Choose how much to mix in community distribution by deferring to a (community) prediction of the form "in retrospect, what weight between model and community would have given the highest score?".
