### ISSUE TITLE
Work with GJOpen

### ISSUE THREAD

**Issue by AABoyles** [oughtinc/ergo#223]
Since [the roadmap](https://github.com/oughtinc/ergo#functionality) explicitly states that the destination for ergo is

> Interfaces for all prediction platforms

Sooner or later extending ergo to work with [GJOpen](https://gjopen.com/) will be necessary. Annoyingly GJOpen doesn't appear to have an open API, and is rendered server-side, meaning that accessing data will require scraping html. I can find two instances of code that already does this:

* [gjopen-utilities](https://github.com/hemmendinger/gjopen-utilities)
* [gjo_search](https://github.com/zarak/gjo_search)

**Comment by AABoyles** [comment]
Tangentially related: [IARPA published GJP's data.](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/BPCDH5) It's older (2016) and isn't a perfect apples-to-apples match to the data coming out of GJO, but could be useful anyway.

**Comment by stuhlmueller** [comment]
Between PredictIt and GJOpen, which one would you prefer if you could only have one? Are there other platforms we should be thinking about?

**Comment by AABoyles** [comment]
All else being equal and given only one, I'd choose GJOpen.

Others of which I'm aware:

* [PredictionBook](https://predictionbook.com/)
* [Almanis](https://www.almanis.com/)
* [FredCast](https://research.stlouisfed.org/useraccount/fredcast/) (Specific to questions of interest to the St. Louis Federal Reserve Bank
* [Augur](https://www.augur.net/)
* [Hypermind](https://predict.hypermind.com/hypermind/app.html#welcome)
* [Predictious](https://www.predictious.com/)

Would you prefer I not leave a new issue for each potential new platform?

**Comment by stuhlmueller** [comment]
For the most important platforms (GJO, PredictIt), one issue per platform is good. Then I'd make another one to capture the long tail of platforms.
