### ISSUE TITLE
Local development workflow for ergo/jupyter notebooks

### ISSUE THREAD

**Issue by william-r-s** [oughtinc/ergo#23]
Right now, it's pretty annoying to develop on ergo for a colab, because you need ot make changes to ergo locally, then push to a git branch, then reinstall it in the colab. Would be better to work on jupyter notebooks locally, with a locally installed dev version of ergo (with `pip install -e .`). But I think we're missing some thinge for that (setup.py)

**Comment by stuhlmueller** [comment]
Note that colab can also connect to a local jupyter notebook server

**Comment by stuhlmueller** [comment]
https://ergo.ought.org/en/latest/workflow.html
