### ISSUE TITLE
Add additional forecasting platforms

### ISSUE THREAD

**Issue by AABoyles** [oughtinc/ergo#232]
Beside [PredictIt](https://github.com/oughtinc/ergo/issues/147) and [GJO](https://github.com/oughtinc/ergo/issues/223), there are a number of other forecasting platforms and prediction markets out there. A likely incomplete list:

* Facebook [Forecast](https://forecastapp.net/)
* [Good Judgment Open](https://www.gjopen.com/)
* [PredictionBook](https://predictionbook.com/)
* [Almanis](https://www.almanis.com/)
* [FredCast](https://research.stlouisfed.org/useraccount/fredcast/)
* [Augur](https://www.augur.net/)
* [Hypermind](https://predict.hypermind.com/hypermind/app.html#welcome)
* [Predictious](https://www.predictious.com/)

Long term, maybe ergo can wrap some/all of these.

**Comment by stuhlmueller** [comment]
- Facebook [Forecast](https://forecastapp.net/)

**Comment by zmpster** [comment]
I'm going to start with a simple read-only integration with Almanis, because they have a relatively easy to use API. I'm going to start by just being able to get question texts, and current probabilities for binary questions. Does this seem like a sensible next step?
