### ISSUE TITLE
More informative error when user must provide bandwidth for plot

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#238]
As seen [here](https://colab.research.google.com/drive/1v5-5ATlsVMtFEO8O8vpVH1ILOz0RseQx#scrollTo=5Us0Tau4TLRY&line=1&uniqifier=1)

**Comment by brachbach** [comment]
Ah now that I'm running this locally, I see the error messages re: bandwidth that you added in

(not sure why they don't show up in that Colab, guessing I somehow got the versioning of ergo wrong there)

I do think it'd be nice to give the user a bit more guidance about what the bandwidth is and how to play with it

maybe a link to an explanation?

Ideally, assume that this is the least-technical person possible who's running into this -- they know enough Python to call the plotting function, but have no idea what a bandwidth is

**Comment by djthorne** [comment]
@brachbach The error string currently reads 

> The plot was unable to automatically determine a bandwidth. You can manually specify one with the keyword 'bw', e.g., show_prediction(..., bw=.1)

Happy to iterate, but would appreciate suggestions. The annoying thing is that they literally have to insert different bw numbers until it looks reasonable. I'm making a new issue to look into the error message not showing up on the collab

**Comment by djthorne** [comment]
I think the visibility issue is the main problem. Pending the results of https://github.com/oughtinc/ergo/issues/239 I think my quick fix to this is to put the error message in an exception, not rely on the print statement

**Comment by brachbach** [comment]
Yeah I saw the error string when I ran it locally -- it would be nice if it told me how to experiment, or explained what the bandwidth was, or something like that

When I saw it, I first tried 0.1, then 1, then 0.01, which did seem like a pretty good strategy

so maybe we should just tell people to do that?

but maybe you have a better way?

**Comment by djthorne** [comment]
I think the whole issue is that the correct number is dependent upon the particular characteristics of their distribution so it is hard to give good advice beyond (slight adaptation from the ggplot docs):
"Explore multiple widths to find the best value to illustrate the stories in your data"

**Comment by brachbach** [comment]
cool got it. yeah then seems good to just say something like that, or link to where ggplot docs say that
