### ISSUE TITLE
Number in text looks off in in el-paso-workflow notebook

### ISSUE THREAD

**Issue by erose** [oughtinc/ergo#282]
Hi, I was reading the [El Paso workflow](https://github.com/oughtinc/ergo/blob/master/notebooks/build/el-paso-workflow.ipynb) notebook to learn a bit, and I found this confusing.

> What is my 90% confidence interval for the number of ventilators needed? I think there is a
>
>    * less than 5% chance that <3 people require ventilation
>    * less than 5% chance that >1000 people require ventilation
>
> So I'll go with a 90% confidence interval of [3, 100].

Should it be "less than 5% chance that > **100** people require ventilation"? Or maybe I misunderstand?

It looks like this may already be addressed in https://github.com/oughtinc/ergo/pull/268; feel free to close if so!

**Comment by brachbach** [comment]
Thanks for pointing this out!

I do think it's addressed by #268.

**Comment by erose** [comment]
Sounds good, I'll close.

**Comment by brachbach** [comment]
@erose FYI we just merged the [new version of the notebook](https://github.com/oughtinc/ergo/blob/master/notebooks/build/el-paso-workflow.ipynb)

I'd be interested in your feedback on it if you check it out!
