### ISSUE TITLE
Investigate logistic.fit_mixture when scale/support ratio is too low

### ISSUE THREAD

**Issue by djthorne** [oughtinc/ergo#289]
The fit_mixture function is fairly robust. However, one class of mixtures it has difficulty recovering---when the support of the mixture is large and the individual distributions have small scales relative to this large domain.

**Comment by stuhlmueller** [comment]
Provide examples?

**Comment by djthorne** [comment]
https://colab.research.google.com/drive/1h_Cbb_ogez6NaLfFFpX4flgGXTE1LCdK?usp=sharing

Seems like the ratio has to be > 1%   with it being more reliable when it is >5%
