### ISSUE TITLE
Load Metaculus question by URL

### ISSUE THREAD

**Issue by AABoyles** [oughtinc/ergo#305]
When I want to load a Metaculus question using ergo, I:

1. Load the question on metaculus.com in my browser
2. Copy the question id from the URL
3. Paste the question id into my Python script

I'm thinking about step 2 here. Outside of Metaculus' internal admin and Ergo, there isn't a whole lot of use for Metaculus question IDs. Instead, I'd prefer to just copy the whole URL and let Ergo parse out the question ID as necessary.

**Comment by stuhlmueller** [comment]
We could also take the subdomain from the URL.

(We've been working on a tool built on Ergo that uses URLs instead of IDs. We should move that functionality into Ergo.)
