### ISSUE TITLE
Why aren't draws from ergo.<distribution> automatically tagged in models?

### ISSUE THREAD

**Issue by AABoyles** [oughtinc/ergo#314]
When I pick a draw from a Community Distribution in a model, it's automatically tagged in the output and I don't need to do anything else. When I pick a draw from a parameterized distribution, I need to tag it in order to get its output. This is sort of a weird distinction, since they're both just drawing from a distribution. It would be cool and convenient if we could optionally pass a `name` argument to the distributions that the model could pick up and include automatically.

**Comment by stuhlmueller** [comment]
You kind of can:

```py
ergo.normal_from_interval(0, 10, name="my name")
ergo.beta(0, 1, name="my second name")
```

I agree that we need a more consistent approach to the use of names. One version of that could be that names are passed into distribution constructors like `NormalFromInterval`.

**Comment by AABoyles** [comment]
Oh, that's embarrassing! My mistake for not trying it first :)
