### ISSUE TITLE
community_dist -> denormalize_samples error

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#329]
I tried to apply Elicit to [this question](https://pandemic.metaculus.com/questions/4400/by-august-1-how-many-tests-for-covid-19-will-have-been-administered-in-the-us/).

Got this error from Ergo:
```
  File "/Users/stuhlmueller/Projects/elicit/app.py", line 93, in load_starting_dist
    community_dist = q.community_dist()
  File "/Users/stuhlmueller/Projects/ergo/ergo/platforms/metaculus/question/continuous.py", line 158, in community_dist
    self.denormalize_samples(self.prediction_histogram[-1][0])
  File "/Users/stuhlmueller/Projects/ergo/ergo/platforms/metaculus/question/log.py", line 59, in denormalize_samples
    return [self.true_from_normalized_value(sample) for sample in samples]
TypeError: 'float' object is not iterable
```

[Responsible code](https://github.com/oughtinc/ergo/blame/0f43f36619023817f015353b45eaca758c76b6b2/ergo/platforms/metaculus/question/continuous.py#L157)

**Comment by brachbach** [comment]
@stuhlmueller the reason this doesn't work is because the question is on a log scale. I'll have the backend send an appropriate error back to the frontend for questions that are not linear, and then show something on the frontend.

I'll also finish my bookmarklet that you can use on a Metaculus question page to go to Elicit, which will tell you if you're trying to do non-LinearQuestion

**Comment by stuhlmueller** [comment]
It seems like a strange error though? In the linked code, `self.denormalize_samples` sounds like it should apply to an array but it's applied to a float?

**Comment by brachbach** [comment]
Yeah -- there's something weird going on with the types.

I'm planning to add a `normalize_value` function for all LinearQuestion subclasses and just use that, which should solve the problem (currently this is like my [4th-next thing to do](https://ought-inc.slack.com/archives/C011D2AF0BH/p1590113249040200) )
