### ISSUE TITLE
Support Python 3.7.* and 3.8.*

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#412]

**Comment by stuhlmueller** [comment]
PR #411 demonstrates that 3.7 and 3.8 are not currently supported.

**Comment by NixGD** [comment]
PR #414 is an attempt to fix this.

**Comment by peterhurford** [comment]
Perhaps with https://github.com/oughtinc/ergo/pull/415 we can close this issue? Though we would need something like https://github.com/oughtinc/ergo/pull/430 to fix the error on installation
