### ISSUE TITLE
Change density functions to accept arraylike inputs

### ISSUE THREAD

**Issue by NixGD** [oughtinc/ergo#418]
Currently, the `pdf`, `logpdf`, `cdf`, and `ppf` for distributions only accept single points.  It should be fairly easy to have them accept arbitrarily-shaped arrays as well.

Some benefits of doing so:
- can make code that calls these functions a lot cleaner by getting rid of list comprehensions.
- allows for pretty dramatic speedups by using numpy's (or jax's, I guess) builtin vectorization in the calculations.  Getting 100 pdfs values from a logistic mixture takes almost a full second as is; this could be done in milliseconds.  This would be especially nice for graphing distributions.
- it would more closely match the interface of scipy distributions.

Disadvantages:
- makes the density-functions themselves harder to understand (one needs to keep track of axes order, etc).
- takes development time (although I would be happy to take this on)

Any thoughts on if this seems worthwhile?

**Comment by stuhlmueller** [comment]
I think it's worth doing if there aren't unexpected difficulties.
