### ISSUE TITLE
Quickstart notebook requires entering username and password in plaintext

### ISSUE THREAD

**Issue by zmpster** [oughtinc/ergo#424]
This is probably not a huge issue, but the quickstart notebook requires entering one's Metaculus username/password in plaintext, which made me uncomfortable, and also makes it so you cannot share any potential changes of the notebook to anyone else.

**Comment by zmpster** [comment]
I'm planning to submit a PR once I get my setup working.

**Comment by zmpster** [comment]
Actually, it looks like you don't need the login line at all, as the "get_question" function doesn't even require login. It feels like we should just remove the login lines?

**Comment by stuhlmueller** [comment]
Yeah no longer needed!
