### ISSUE TITLE
Implement changes suggested by PullRequest

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#50]
Go through all recent PRs, implement any suggestions from PullRequest that we haven't implemented yet.

"Why are you converting e.args, e.request.body and e.response.json() to strings?"

**Comment by stuhlmueller** [comment]
- Ben's PR
- William's last PR

**Comment by brachbach** [comment]
- BR docs PR
- go through recent PRs and see if there are any for which we didn't implement PullRequest's advice

**Comment by stuhlmueller** [comment]
- Some of my PRs

We might want a convention for marking PR comments that have been addressed (some emoticon reaction).

**Comment by brachbach** [comment]
Cool yeah, when I do this I'll think about what the ideal workflow would be
