### ISSUE TITLE
Add prediction submission to Foretold API

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#54]
Given measurement id and model samples, submit distribution to [Foretold](https://www.foretold.io/)
    - Convert samples to CDF of xs and ys, same format we get back from Foretold
    - Need API token (Profile > Bots > New Bot > Token)
    - Every call also submits the token

**Comment by brachbach** [comment]
why do we want to be able to do this, exactly? (makes sense in general, but what do we want to do with it in the near term?)

**Comment by stuhlmueller** [comment]
Don't know yet whether it makes sense in short term but if we wanted to implement [step 2 here](https://docs.google.com/document/d/1rTb4D8dF0vGRuHVZZsi8sOfk4htBbCqgQdOTziywih4/edit#heading=h.di6kk4h3ud1j) we'd need it.

**Comment by stuhlmueller** [comment]
Create example that shows how to keep a Foretold questions synced to latest Metaculus community prediction

**Comment by null-a** [comment]
Here's [some information](https://observablehq.com/@jjj/bot-tips) about the Foretold API for reference.
