### ISSUE TITLE
Compute minimal update to (community) distributions that makes them consistent with model

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#59]
Compute minimal adjustment necessary to achieve consistency. 

https://en.wikipedia.org/wiki/Earth_mover%27s_distance

**Comment by stuhlmueller** [comment]
Make version of infections/deaths/ratio example that updates all there variables

**Comment by AABoyles** [comment]
Some extensions:

- Weight by credence: pass in a list of credences you assign to the community distribution on each question and adjust the question in proportion to (some function of) those credences.
- Weight by census: adjust the question according to some function of the number of predictions or predictors (or both), relative to the number of predictions (or predictors or both) on the other questions being optimized against.

([Crossposted](https://github.com/oughtinc/ergo/issues/174#issuecomment-619212033) at @stuhlmueller's request from #174)
