### ISSUE TITLE
Search questions on predictions platforms

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#78]

**Comment by zmpster** [comment]
Can someone provide a little more info here? Is the idea to integrate with one or more of the prediction platform's search API? And do we just want to add a function that does this?

**Comment by stuhlmueller** [comment]
Thanks for asking! On reflection this is less important than [adding more prediction platforms](https://github.com/oughtinc/ergo/issues/232). For most interesting approaches to search we'd want to load all questions first and not use the platform's API.
