### ISSUE TITLE
Switch from autopep8 to black

### ISSUE THREAD

**Issue by brachbach** [oughtinc/ergo#80]
Black is a fully-opinionated code formatter that aims to automatically format code in one correct way: https://blog.frank-mich.com/python-code-formatters-comparison-black-autopep8-and-yapf/

I don't have strong views on Python style, so I'm sure I'd be happy with it

Seems to me like a no-brainer to switch from autopep8, which is much more permissive

we'd want to run it over all the files, then switch what people use locally

ideally we'd also run it on Github when push, but I don't think that's terribly important

@stuhlmueller LMK if you don't want me to go ahead and make the switch

**Comment by brachbach** [comment]
[docs](https://black.readthedocs.io/en/stable/)

**Comment by stuhlmueller** [comment]
Probably fine. Would want to look at our files before/after reformatting to decide.

**Comment by brachbach** [comment]
Comment from PullRequest: https://github.com/oughtinc/ergo/pull/61/files#r409684033

**Comment by brachbach** [comment]
Done in #82
