### ISSUE TITLE
Support use of Metaculus API without providing username and password

### ISSUE THREAD

**Issue by stuhlmueller** [oughtinc/ergo#89]
Then update quickstart

**Comment by stuhlmueller** [comment]
People should only need to enter their login information if they want to call methods that need it.

**Comment by AABoyles** [comment]
Cheap way to accomplish this quickly: set the default argument values of `username` and `password` to the corresponding values for oughtpublic`. Bonus points for checking that the username on the session isn't oughtpublic before submitting predictions upstream.

**Comment by zmpster** [comment]
I think this is done? `get_question` doesn't require `is_logged_in_via_uname_pwd`
